export const CommentBoxes = [['001','Joey Tribbiani', 'joey_1478@gmail.com', 'So bad.'],
['002', 'Rachel Greene', 'rachel_257@gmail.com', 'Congratulations Sir.'],
['003', 'Phoebe Buffay', 'phoebe_2000@gmail.com', 'I hate politics.'],
['004', 'Ross Geller', 'ross_1118@gmail.com', 'Good job.'],
['005', 'Monica Geller', 'monica_first@gmail.com', 'I love pandas.'],
['006', 'Janice Goralnik', 'janice_98@gmail.com', 'O My God.'],
['007', 'Mike Hannigan', 'mike_355@gmail.com', 'March is the craziest manth.'],
['008', 'Gunther Petterson', 'gunther_centralperk@gmail.com', 'I am not letting my kids eat that things.'],
['009', 'Chandler Bing', 'chandler_bing@gmail.com', 'My favourite actor.'],
]