export const PostsBoxes = [["Tesla to cut around 15,000 jobs under Musk drive for 'productivity' - reports",
 "The electric vehicle maker, founded and run by Elon Musk, was yet to comment on a story earlier on Monday by Electrek that it was to axe about 15,000 personnel."],
 ["Michael Douglas has won Oscars for both acting and producing",
"The 79-year-old is a renowned figure in the film industry having produced and starred in a selection of award-winning films."],
["Deadline to register to vote in local elections this evening", 
"The deadline is fast approaching for voters to be able to cast their ballots on 2 May, when polls are taking place across the country."],
["Three of the 'big four' boiler manufacturers for the UK cannot guarantee customers", "In January boiler-makers hiked costs by up to an extra £120 per boiler to cover anticipated penalties for a green scheme - which has now been delayed."],
["Pandas are not good at reproducing", "Feeding captive pandas a seasonal diet could help them reproduce, according to a new study from Beijing. The species are particularly bad at reproducing, which hampers conservation efforts."],
["Creating fake images of another person to become a criminal offence", "Love Island's Cally Jane Beech has praised the new law, which would see 'malicious' people who create explicit deepfakes face an unlimited fine."],
["A storm wreaked havoc across the UK", "Storm Babet ravaged parts of the country last October, with the Musselburgh coastline suffering a major hit with around 4,000 cubic metres of sediment removed from its beaches."],
["Chemicals' found in more than half of food", "Strawberries were found to be the worst when it came to presenting residues of PFAs, long-lasting toxins which have been linked to serious health issues."],
["Leonardo DiCaprio urges", "The American actor took to Instagram to share the message of the Scottish Rewilding Alliance with his 62.1 million followers."],
]